import { DM_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organisms/navbar";
import LenisScroll from "@/components/scroll/lenis";
import TransitionProvider from "./profiders/transitionProvider";
// import { Analytics } from "@vercel/analytics/next";
// import { SpeedInsights } from "@vercel/speed-insights/next";

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Outrank Website | Landing Page",
  description: "Generated by Outrank Website",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={`${dmMono.className} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col">
        <TransitionProvider>
          <LenisScroll/>
          <Navbar/>
          {children}
          {/* <Analytics/>
          <SpeedInsights/> */}
        </TransitionProvider>
      </body>
    </html>
  );
}
